spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
#      sms:
      #        host: https://fesms.market.alicloudapi.com
      #        path: /sms/
      #        skin: 1
      #        sign: 175622
      #        appcode: b0563c23aff8428c97a54d4f7f9e28e5
      access-key: LTAI5tKGYbFWnebzfjGc6UrJ
      secret-key: HdDSDZWcFOLblwDe6EqtaBAUK9BN1d
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-lucas2
  application:
    name: mall-third-party

server:
  port: 30000
