spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      sms:
        host: http://notifysms.market.alicloudapi.com
        path: /send
        method: POST
        appcode: f045cfc810f549ae8afdda7037ef1516
        template_code: T0001
        sign_name: 复数科技
      access-key: 204445901
      secret-key: PjnaHPwCaVVZ8OdtDLy5kkqaEGtPpFmS
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-lucas2
  application:
    name: mall-third-party

server:
  port: 30000
